### ISSUE TITLE
Error calling mount macro when swimming in Broken Isles

### ISSUE THREAD

**Issue by Malivil** [DanSheps/Bestride#13]
Date: 2018-07-21 08:58:14
ID: 36
Error occured in: Global
Count: 1
Message: ..\AddOns\bestride\Bestride_Logic.lua line 407:
   Usage: UnitBuff("unit", [index][, "filter"])
Debug:
   [C]: UnitBuff()
   bestride\Bestride_Logic.lua:407: Swimming()
   bestride\Bestride_Logic.lua:273: PreClick()
   [string "*:PreClick"]:1:
      [string "*:PreClick"]:1
   [C]: Click()
   ..\FrameXML\ChatFrame.lua:1626: ?()
   ..\FrameXML\ChatFrame.lua:4695:
      ..\FrameXML\ChatFrame.lua:4662
   [C]: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4383:
      ..\FrameXML\ChatFrame.lua:4382
   [C]: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:2874:
      ..\FrameXML\ChatFrame.lua:2867
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:345: handler()
   ..\FrameXML\SecureTemplates.lua:623:
      ..\FrameXML\SecureTemplates.lua:571
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:266:
      ..\FrameXML\SecureHandlers.lua:263
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:296:
      ..\FrameXML\SecureHandlers.lua:279
   (tail call): ?
Locals:
(*temporary) = "player"
(*temporary) = "Water Breathing"

AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  Altoholic, vr183
  Archy, v7.3.2.1
  Atlas, vv1.43.06
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasLegion, vv1.43.03
  AtlasMistsofPandaria, vv1.43.00
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWrathoftheLichKing, vv1.43.01
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  AtlasMajorCitiesEnhanced, vv1.15
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  Bartender4, v4.8.1
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  bestride, v0.0.4
  CTBagMod, v
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v8.0.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  EasyMail, v7.0
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  ExecutiveAssistant, v1.3
  ExtVendor, v1.7.2
  FactionAddict, v1.48
  GarrisonMissionManager, vv55
  GatherMate2, v1.42
  Grail, v095
  HandyNotes, vv1.5.2
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesSuramarTelemancy, v1
  IceHUD, v1.11.2
  Informant, v7.7.6000 (SwimmingSeadragon)
  MasterPlanA, vA
  MouseTooltip, v1.0
  MoveAnything, v17.0.0
  nehFragger, v1.3a
  NPCScan, v8.0.1.2
  Omen, v3.2.0
  OmniCC, v8.0.0
  Overachiever, v1.0.0
  PersonalLootHelper, v2.04
  PetBattleMaster, v7.0.4
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerJournal, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  Prat30, vr1155      
  Prat30Libraries, v
  Quester, v8.0.1.0
  Recount, vv8.0.1a
  sct, v7.1
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  Stubby, v7.7.6000 (SwimmingSeadragon)
  TimerBars, v1.2
  Titan, v5.13.1.70300
  TitanBag, v5.13.1.70300
  TitanClock, v5.13.1.70300
  TitanGold, v5.13.1.70300
  TitanGuild, v7.0.3.4
  TitanLocation, v5.13.1.70300
  TitanLootType, v5.13.1.70300
  TitanMail, v7.35
  TitanPerformance, v5.13.1.70300
  TitanRepair, v5.13.1.70300
  TitanSpeed, v7.3.001
  TitanVolume, v5.13.1.70300
  TitanXP, v5.13.1.70300
  Wholly, v066
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=bde)

**Comment by Daeymien** [comment]
Going to need to treat water breathing buffs the same as Aquatic Form since you can't query UnitBuff() by name any longer. That or step through all active buffs to look for it being active each time. Whichever floats your boat (no pun intended).

**Comment by Daeymien** [comment]
Pull Request with fix submitted
