### ISSUE TITLE
v0.0.5 Error: Unable to open AceDBOptions...

### ISSUE THREAD

**Issue by nancikennedy** [DanSheps/Bestride#14]
4x Couldn't open bestride\libs\AceDB-3.0-26\AceDBOptions-3.0-15.xml

**Comment by DanSheps** [comment]
Does the file exist at the location?

**Comment by nancikennedy** [comment]
No. There's no suffixes (i.e. "-26" and "-15" on any of the included Ace libs

**Comment by DanSheps** [comment]
Could you.try uninstalling and reinstalling the add-on, competely?

Do you have any other add-ons that embed ace or do you have ace3 globally?

**Comment by Daeymien** [comment]
Managed to grab the error having BugGrabber (part that BugSack relies on and hooks the LUA errors) and BugSack.

I can reproduce the error with a number of addons, specifically before the client has access to the queried folder/file and retries. Normally it'll silently fail. On load, Ace goes through and looks at the minor revisions to check if there were any upgrades from last run.

Example:
2x Couldn't open ChatTextures\

That "addon" does literally nothing except list itself in the Addons list. no libs, no script, nada.

So, it would seem BugGrabber is hooking way early in the load process and catching the retries, which would be an issue on their end.

**Comment by Daeymien** [comment]
@DanSheps Might wanna freshen the Libs anyway just to be safe.

**Comment by nancikennedy** [comment]
hehe...I will let it drop then, since it's really just a cosmetic issue for me at this point. No harm being done on my end other than having to look at a red bugsack icon. Thank you for taking the time to discuss this with me. :)

**Comment by Daeymien** [comment]
Just for the sake of posterity:

Woke up and decided to see if I could break things.  Only loaded my dummy addon. Logged in, no errors.  After a /reload, it threw the "Couldn't open...". So, something is going whacko with the client and addons.

**Comment by nancikennedy** [comment]
I really hate those earworms that crawl in and whisper....but, but....I need to KNOW. They've been responsible for more 3am coding sessions than I care to think about anymore.
