### ISSUE TITLE
Only picking flying mounts

### ISSUE THREAD

**Issue by dexxa88** [DanSheps/Bestride#16]
When using the set mount/dismount button the addon seem to only pick flying mounts even when ground mounts have been assigned. When no flying mount has been assigned at all, the addon seem to pick a random flying mount instead.

This happens on several characters on different levels in several different zones. It will always do a flying mount even if no has been assigned almost like it forces flying mounts only.

**Comment by Daeymien** [comment]
Since it wasn't mentioned, if Force Flying Mounts is enabled in Mount Options then this would be the expected behavior.
