### ISSUE TITLE
Retail: Does nothing

### ISSUE THREAD

**Issue by walter-hwhite** [DanSheps/Bestride#191]
### WoW Version

Retail (9.2.5)

### Bestride Version

2.0.0

### Steps to Reproduce

Install addon, try either the macro or the keybind. 

### Observed Behavior

Disabled all addons except for BeStride, but neither the /click macro or the keybind work. 
No error messages, it just does nothing. 

Able to open the GUI and make selections.

**Comment by matt-stuart** [comment]
This worked for me, can do it yourself until there's a bigger update.

https://github.com/Bestride/BeStride/pull/192

**Comment by walter-hwhite** [comment]
Thank you for the tips. That fixed the hotkey at least, but the macro still did nothing. After some googling I changed it to 
`/click BeStride_ABRegularMount MouseButton Down` 
That seemed to work.
