### ISSUE TITLE
Bestride isn't working anymore in either of the Alpha or Beta formats!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#23]
Hi.

Love your addon and been using it for ages.  I have a problem only with the Alpha and Beta versions and will explain below.  I am only informing you to let you know, as they are in Alpha and Beta one can expect errors or problems and you want and need people to try them :).

Since v0.5.0-alpha4 through and including v0.5.0-beta-2, in game I get no errors at all, but the addon doesn't even seem to exist on my interface list to get to the options menu and the key binding also doesn't work as it appears there is no addon active.  It is on the addons list screen ticket correctly, but not available in game in the interface menu where I can select mounts and options etc. normally.  When I go back to the last release v0.0.11 I have no issues at all and all works well.  I have also deleted everything many times (including saved Variables) and I am unable to get it to work at all.  I hope this helps and maybe you are already aware of this issue?  I am on EN-US client on Oceanic Server both Horde and Alliance with multiple classes and races with the same problem on all.

On another note that I probably should put another ticket in for?  But on my Demon Hunter I am unable to use the key binding to rush forward with [Fel Rush](https://www.wowhead.com/spell=195072/fel-rush) 195072.  I know some addons in the past used this and am not sure if you plan to or not, although I hope you do and are going to soon please?  It is really handy to have as a key binding, but I would like it like the mage does blink and the Monk Roll etc.  I am not sure if others would like an option to have it off or on, as you do many other classes and one of the things that makes your addon so awesome as well as many other things.  If you want another ticket for this please let me know and I will submit one.

Thanks in advance,

Mindlessgalaxy.

**Comment by DanSheps** [comment]
Please open a new issue for gel rush, I can most likely add that in before I push out the final version.

As for the other issues.

Can you type /br and see if that opens the interface?

I might also break out the keybind issue into another issue as it is most likely due to the fact that I am using a different manner to bind keys.

**Comment by Mindlessgalaxy** [comment]
Hi Just me again.

I just noticed in Buggrabber I got this error and not sure what it is for or in aid of, but hope it can help?  If you want this in another ticket let me know please, but I assume it is to do with what we have been talking about, or am hoping so?

2x BeStride\BeStride-0.5.0.lua:212: attempt to call method 'Info' (a nil value)
BeStride\BeStride-0.5.0.lua:212: in function <BeStride\BeStride.lua:211>
[C]: in function `foreach'
BeStride\BeStride-0.5.0.lua:211: in function `Upgrade'
BeStride\BeStride-0.5.0.lua:159: in function <BeStride\BeStride.lua:149>
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
ArkInventory\ArkInventory-30815.lua:10151: in function `LoadAddOn'
ArkInventory\ArkInventory-30815.lua:10162: in function `BlizzardAPIHook'
ArkInventory\ArkInventory-30815.lua:2511: in function <ArkInventory\ArkInventory.lua:2501>
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:489: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1194: in function <FrameXML\UIParent.lua:1090>

Thanks again...

**Comment by DanSheps** [comment]
I have pushed a new beta.  It will most likely take awhile to be approved but if you give it a try it should fix everything.
