### ISSUE TITLE
Fel Rush Key Binding Function Please?

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#24]
Hi Again,

I was hoping that on my Demon Hunter I could use the key binding to rush forward with [Fel Rush](https://www.wowhead.com/spell=195072/fel-rush) 195072. I know some addons in the past used this and am not sure if you plan to or not, although I hope you do and are going to soon please? It is really handy to have as a key binding, but I would like it like the mage does blink and the Monk Roll etc. I am not sure if others would like an option to have it off or on, as you do many other classes and one of the things that makes your addon so awesome as well as many other things.  Thanks for seriously considering this and I just mostly cut and pasted my request, hope you don't mind?

Thanks in advance,

Mindlessgalaxy.

**Comment by Mindlessgalaxy** [comment]
This is working in part, but not completely.  What is happening now with Beta version 4 is that all classes work well outside of any instances, but when doing instances I cannot get class abilities to work at all and only get the message "Cannot do that while moving".  As I said works everywhere but not in dungeons or instances for me.  The old version does work fine, just assume something with the code is either wrong or something, sorry I cannot help more.

**Comment by Mindlessgalaxy** [comment]
This is working now for all toons and relevant classes, however it is not working in any of the instances for me at all.  Using Beta Version 4 it just keeps giving me the message, " Cannot do that while moving".  Works everywhere else, but I haven't tried combat either lol.  I am also having trouble as mentioned in another ticket with posting to this site.  Not sure what is going on, but I have created duplicate tickets and then they vanish, so a little confused and leaving for the night and will try again tomorrow with some more information to hopefully help out and I also hope you don't mind all the feedback I am giving?  Just don't want to cause to much extra work and very aware it is only Alpha and Beta, and that is why you were doing this and wanting feedback for those who don't mind errors etc lol.

**Comment by DanSheps** [comment]
Only on the demon hunter though, right?
