### ISSUE TITLE
Not Selecting A Random Mount I Have Selected!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#26]
Hi yet again.

If you prefer not to have tickets for each item please let me know and I will do whatever you want or need me to, especially out of appreciation for all you do for all of us :).

When I mount I often get a random mount that is not selected and the most common one so far on Alliance toons is Swift Purple Griffon or often one of those ones so far, and then it will eventually select one I want.  I also **_do not_** have the option ticked to select any mount of none are selected.

I am going back to the release version now just to play, but let me know if you want me to do more or anything else to help out and again sorry for the delay in putting in tickets, although I thought it wasn't working, which yep I should have also reported.

All the best and thanks once again :))

**Comment by Mindlessgalaxy** [comment]
Hi.

This is working well with the new version Beta 4.

Thanks for that and I think you can now close this unless you need to do more yourself?

**Comment by Mindlessgalaxy** [comment]
This is now working well for me, so if you want to close it all seems well since Beta 4 :)

**Comment by DanSheps** [comment]
Leaving this open to be resolved by the push to master when done
