### ISSUE TITLE
No Profiles Selectable!  Only with The Alpha and All Beta Versions!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#38]
Hi Again,

I assume you are aware of this, but just in case I would put this ticket in and just close it if you want?

I am not able to select profiles for any toons at all regardless of faction.  I have set it up and everything is working well now, but Horde and Alliance have to be setup first for each faction and then it is fine and must be the default as a faction base or the like?

Also I have put a few tickets in as you will see and for some reason having great issue with submitting tickets and getting back to the duplicates that I didn't realised had been submitted.  Could you please delete the duplicates for me and I will add some more tickets when the site is actually working properly again or whatever is going on?

Thanks again,

Mindlessgalaxy,

**Comment by DanSheps** [comment]
This isn't implemented yet, should be shortly though.  Hopefully.  Look for the next Beta.

Also, no worries about the tickets, apparently Github was a trainwreck last night.
