### ISSUE TITLE
Debug Error On Monk Only!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#39]
Hi Again,

Using Beta Version 4 I am getting this error only on my Monk Alliance level 87.

[Debug] Fatal Unmatch (Pioritizepassanger)

It gives me that in the general chat frame each time I log onto the toon. Again I hope this helps out and if you prefer me not to submit so many or anymore tickets just let me know, as I am not sure what issues you are aware of or not and I play every class but only 3 are below 90.  Also both horde and ally and I obviously don't mind helping you out whenever you want or need anything, just crap at coding myself.

**Comment by DanSheps** [comment]
Could you try the latest, I can't seem to get this to fire.
