### ISSUE TITLE
mount macros

### ISSUE THREAD

**Issue by ClockworkGod** [DanSheps/Bestride#4]
the macro commands from yaymounts now do absolutely nothing. I do not think the buttons are actually getting populated, as they don't show up in my frame mover addon, where with yaymounts they did.

**Comment by DanSheps** [comment]
Are you talking about the /click YayMountsButton macros?

**Comment by ClockworkGod** [comment]
yeah, i wad using this macro for years:

#showtooltips Bloodbathed Frostbrood Vanquisher
/cast [mod:ctrl,swimming] Sea Turtle; [swimming] Azure Water Strider
/click [mod:ctrl] YayMountsButton2; [noswimming] YayMountsButton
/dismount
/run VehicleExit();
/run UIErrorsFrame:Clear();

is there a new way to do this now? it's been a while since I played.

**Comment by ClockworkGod** [comment]
i am more of an idiot than I like to admit, I downloaded this from curse and did't see any of the documentation that is here on github.
