### ISSUE TITLE
Beta Version 7 Not Working At All!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#45]
Hi Again,

Just letting you know that even with a fresh install of Beta Version 7 there is no addon functioning in the game at all.  I have tried /br and nothing happens and no bindings either, I suppose that would be obvious.  It is correctly ticket for my toons, just not functional.

Also with Beta 6 that I gave a try.  The key bindings only work with Class Actions only and no mounts are summoned at all, but the options are all there and everything seems correct and in order.  So for now I have gone back to version Beta 5 until I hear back from you about what has happened?

Will also let you know about the Monk debug issue once the above issues are resolved, as no point if it has already been corrected, but I haven't logged into all toons to see the above issues only 2 of them.

Thanks heaps again for all your hard work. it is very much appreciated :)

**Comment by Mindlessgalaxy** [comment]
Forgot the most important thing, the error logs.  I cannot remember which version these errors popped up, but think it was the first one version 7?

8x BeStride\BeStride_GUI.lua:13: '=' expected near 'BeStride_GUI'


Locals:

Then the rest are Version 6?

115x BeStride\BeStride_Mount.lua:6: attempt to concatenate local 'spell' (a nil value)
BeStride\BeStride_Mount.lua:6: in function `MountSpell'
BeStride\BeStride_Mount.lua:155: in function <BeStride\BeStride_Mount.lua:154>
(tail call): ?
BeStride\BeStride_ActionButton.lua:46: in function `PreClick'
BeStride\BeStride_ActionButton.lua:25: in function <BeStride\BeStride_ActionButton.lua:25>

Locals:
self = <table> {
 PriestLevitate = <function> defined @BeStride\BeStride_Mount.lua:213
 Mount = <function> defined @BeStride\BeStride_Mount.lua:9
 Flying = <function> defined @BeStride\BeStride_Mount.lua:82
 Failback = <function> defined @BeStride\BeStride_Mount.lua:53
 Shaman = <function> defined @BeStride\BeStride_Mount.lua:253
 DemonHunterFelRush = <function> defined @BeStride\BeStride_Mount.lua:180
 Repair = <function> defined @BeStride\BeStride_Mount.lua:122
 RogueSprint = <function> defined @BeStride\BeStride_Mount.lua:265
 Rogue = <function> defined @BeStride\BeStride_Mount.lua:261
 DruidTravel = <function> defined @BeStride\BeStride_Mount.lua:209
 PaladinDivineSteed = <function> defined @BeStride\BeStride_Mount.lua:249
 Paladin = <function> defined @BeStride\BeStride_Mount.lua:245
 MonkZenFlight = <function> defined @BeStride\BeStride_Mount.lua:241
 DruidAquaticForm = <function> defined @BeStride\BeStride_Mount.lua:206
 MageBlinkNoSlowFall = <function> defined @BeStride\BeStride_Mount.lua:227
 MageBlink = <function> defined @BeStride\BeStride_Mount.lua:222
 MageSlowFall = <function> defined @BeStride\BeStride_Mount.lua:217
 DBGetMountStatus = <function> defined @BeStride\BeStride_Mount.lua:30
 Ground = <function> defined @BeStride\BeStride_Mount.lua:94
 DemonHunterGlide = <function> defined @BeStride\BeStride_Mount.lua:184
 MountSpell = <function> defined @BeStride\BeStride_Mount.lua:3
 DeathKnightWraithWalk = <function> defined @BeStride\BeStride_Mount.lua:176
 DoMount = <function> defined @BeStride\BeStride_Mount.lua:20
 DruidFlying = <function> defined @BeStride\BeStride_Mount.lua:202
 ShamanGhostWolf = <function> defined @BeStride\BeStride_Mount.lua:257
 CountRepairMounts = <function> defined @BeStride\BeStride_Mount.lua:17
 IsUsable = <function> defined @BeStride\BeStride_Mount.lua:43
 Swimming = <function> defined @BeStride\BeStride_Mount.lua:106
 MonkRoll = <function> defined @BeStride\BeStride_Mount.lua:232
 Druid = <function> defined @BeStride\BeStride_Mount.lua:188
 Passenger = <function> defined @BeStride\BeStride_Mount.lua:138
 Regular = <function> defined @BeStride\BeStride_Mount.lua:66
 Chauffeur = <function> defined @BeStride\BeStride_Mount.lua:164
 Broom = <function> defined @BeStride\BeStride_Mount.lua:154
 Loaned = <function> defined @BeStride\BeStride_Mount.lua:158
 Nagrand = <function> defined @BeStride\BeStride_Mount.lua:172
}
spell = nil
(*temporary) = "/cast "
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'spell' (a nil value)"

I think the above is showing why Version 6 won't even call a mount and the Version 7 isn't being recognised by my interface, although I am not into coding only an old IT guy lol.

Thanks again and hope the extra info helps a bit?

Mindlessgalaxy

**Comment by DanSheps** [comment]
New release, could you give it a try?

**Comment by DanSheps** [comment]
Please let me know if this resolves it
