### ISSUE TITLE
Passenger mount

### ISSUE THREAD

**Issue by wolfrunner86** [DanSheps/Bestride#5]
any time i try to spawn a passenger mount i get an error 

Date: 2018-04-16 16:48:19
ID: 1
Error occured in: Global
Count: 1
Message: Usage: local name, spellID, icon, isActive, isUsable, sourceType, isFavorite, isFactionSpecific, faction, shouldHideOnChar, isCollected, mountID = C_MountJournal.GetMountInfoByID(mountID)
Debug:
   [C]: ?
   [C]: GetMountInfoByID()
   bestride\Bestride.lua:219: IsUsableMount()
   bestride\Bestride_Logic.lua:90: BuildPassengerTable()
   bestride\Bestride_Logic.lua:154: Mounting()
   bestride\Bestride_Logic.lua:273: PreClick()
   bestride\Bestride_Logic.lua:306: ForcePassengerMount()
   [string "*:PreClick"]:1:
      [string "*:PreClick"]:1
Locals:

AddOns:
  KalielsTracker, v2.1.9
  Swatter, v7.6.5736 (TasmanianThylacine)
  AdvancedInterfaceOptions, v1.2.2
  AllPlayed, vv70100-1
  Altoholic, vr183
  AucAdvanced, v7.6.5736 (TasmanianThylacine)
  AucFilterBasic, v7.6.5736 (TasmanianThylacine)
  AucFilterOutlier, v7.6.5736.5459(/embedded)
  AucMatchUndercut, v7.6.5736.5585(/embedded)
  AucStatHistogram, v7.6.5736 (TasmanianThylacine)
  AucStatiLevel, v7.6.5736 (TasmanianThylacine)
  AucStatPurchased, v7.6.5736 (TasmanianThylacine)
  AucStatSales, v7.6.5736.5598(/embedded)
  AucStatSimple, v7.6.5736 (TasmanianThylacine)
  AucStatStdDev, v7.6.5736 (TasmanianThylacine)
  AucStatWOWEcon, v7.6.5736.5613(/embedded)
  AucUtilAHWindowControl, v7.6.5736.5575(/embedded)
  AucUtilAppraiser, v7.6.5736.5727(/embedded)
  AucUtilAskPrice, v7.6.5736.5599(/embedded)
  AucUtilAutoMagic, v7.6.5736.5732(/embedded)
  AucUtilCompactUI, v7.6.5736.5715(/embedded)
  AucUtilEasyBuyout, v7.6.5736.5725(/embedded)
  AucUtilFixAH, v7.6.5736 (TasmanianThylacine)
  AucUtilItemSuggest, v7.6.5736.5651(/embedded)
  AucUtilPriceLevel, v7.6.5736.5633(/embedded)
  AucUtilScanButton, v7.6.5736.5631(/embedded)
  AucUtilScanFinish, v7.6.5736.5725(/embedded)
  AucUtilScanProgress, v7.6.5736.4979(/embedded)
  AucUtilScanStart, v7.6.5736.5725(/embedded)
  AucUtilSearchUI, v7.6.5736.5731(/embedded)
  AucUtilSimpleAuction, v7.6.5736.5705(/embedded)
  AucUtilVendMarkup, v7.6.5736.4828(/embedded)
  AutoTurnIn, v7.0.9
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.6.5736 (TasmanianThylacine)
  bestride, v0.0.2
  CanIMogIt, v7.3.5v1.7.1
  Collectinator, v7.2.5.1
  Configator, v5.1.DEV.434(/embedded)
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v7.3.26
  DBMDefaultSkin, v
  DBMLDB, v
  DBMNightholdDBH, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Elephant, v3.7.5
  FishingBuddy, v1.8.4.2
  FloFlyout, v
  GatherMate2, v1.41
  GryphonsRemover, vv7.3
  HandyNotes, vv1.4.15
  HandyNotesDraenorTreasures, v1.20a
  Identity2, v3.4.1
  LibExtraTip, v5.12.DEV.435(/embedded)
  MasterPlanA, vA
  MaxDps, v7.3.0.1
  mOnArsWardrobeHelper, v1.17.1
  MountFarmHelper, v7.1.0
  MoveAnything, v16.3.2
  NomiCakes, v7.3.0.1
  NugMiniPet, v
  Overachiever, v0.99.10
  Paste, v1.4.10
  Pawn, v2.2.18
  QuestGuru, v2.4.32
  QuestGuruSounds, v2.4.32
  RaidAchieveFilter, v1.9.8
  RaiderIO, v7.3.5 (v201804161532)
  RaiderIODBUSA, v
  RaiderIODBUSH, v
  RCLootCouncil, v2.7.9
  Recount, vv7.3.5b
  SellJunk, v3.0.15
  Simulationcraft, v1.9.1
  Skillet, v3.34
  Stubby, v7.6.5736 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.13.1.70300
  TitanBag, v5.13.1.70300
  TitanClock, v5.13.1.70300
  TitanCurrenciesMulti, v5.28
  TitanGold, v5.13.1.70300
  TitanLocation, v5.13.1.70300
  TitanLootType, v5.13.1.70300
  TitanPerformance, v5.13.1.70300
  TitanRepair, v5.13.1.70300
  TitanSpeed, v7.3.001
  TitanVolume, v5.13.1.70300
  TitanXP, v5.13.1.70300
  TomTom, vv70300-1.0.0
  TradeSkillMaster, vv3.6.42
  TradeSkillMasterAccounting, vv3.0.20
  TradeSkillMasterAppHelper, vv3.0.4
  TradeSkillMasterAuctionDB, vv3.1.18
  TradeSkillMasterAuctioning, vv3.0.16
  TradeSkillMasterDestroying, vv3.1.7
  TradeSkillMasterMailing, vv3.0.18
  TradeSkillMasterShopping, vv3.4.7
  TradeSkillMasterVendoring, vv3.0.7
  TradeSkillMasterWarehousing, vv3.0.8
  TransmogTokens, v1.4.8
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=edf)

**Comment by DanSheps** [comment]
I will look at this around the 28th.
