### ISSUE TITLE
Filter Issue and Reseting All Mounts!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#54]
Hi,

If I use filters with Beta Version 11 it resets all the mounts and ticks them all again, which is a little annoying.

Also if you unselect all the other tabs also get reset and everything is reselected and all done for nothing.

I put this as one ticket as assume it is linked?

**Comment by DanSheps** [comment]
I am not seeing any issues with the filter, it leaves them ticked/unticked as intended.

I am however seeing an issue with select all/clear all which I will work to resolve shortly.  I will break that out into a new issue.

**Comment by Mindlessgalaxy** [comment]
Bugger that is what I meant. Sorry about that, I shouldn't put tickets in at 3am lol.  At least you know I am only trying to help, so hope you accept my apology for stuffing this up and you worked out exactly what I meant somehow lol.

Thanks again and sorry for not being clear.

Mindlessgalaxy.
