### ISSUE TITLE
Unbelievable :).

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#60]

**Comment by Mindlessgalaxy** [comment]
No errors or problems at all to report 🥇 , everything as far as I can tell is working not just well but perfectly 👍 .  I think you could easily go to release version now if you are comfortable and thank you for allowing me to assist you with your addon and awesome work as well as effort.  I love this addon and it has been fun playing a tiny part in it and now it is so far beyond the best and any other out there.

I will miss doing the reporting and helping out, although I am sure in the future you may want someone to look at some addons or this one again and I would love to help you out if you want or need any feedback.

All the best and again thanks for the fun and being a part of something I love to be part of.

Mindlessgalaxy,

PS:  Not sure what happened to cause the blank first part to the ticket, but just delete this or close it, whenever you are ready 👍

**Comment by DanSheps** [comment]
Thanks for the update!
