### ISSUE TITLE
travel form bug 1.0.1

### ISSUE THREAD

**Issue by wolfrunner86** [DanSheps/Bestride#63]
since the update 1.0.1 i can not cast my travel form on druid when in combat

**Comment by DanSheps** [comment]
Are you horde or alliance?

**Comment by Mindlessgalaxy** [comment]
Hi.

I have tried everything I can and it works in every situation I have tried with an Alliance Worgen Druid Level 111 (not tried Horde, as I don't have one, but willing to create one if you think it helps).  It goes into travel from perfectly and out as well.  I was wondering though if it was possible to add another thing to the Druid Key bindings, but will put in a separate ticket for that.

Wolfrunner86, something I would recommend you could try, unless you already have?  Have you deleted all old files including Saved Variables and then reinstall to see how that goes for you? I only mention it, as it often happens with addons that a file can get corrupted at some point.  Also with big changed to addons it is often best to start from fresh regardless.  Hope the helps and if none of it is relevant to you, sorry to hassle you with the suggestions,

All the best,

Mindlessgalaxy.

**Comment by wolfrunner86** [comment]
OK so of 4 druids only 1 can change enable/disable travel form using the mount hotkey, the other 3 cant i have 2 of each faction. completely uninstalled the addon and setting via the twitch launcher and double checked b4 i reinstalled that everything was gone. re tested all 4 toons and only the 1 druid can toggle travel form when in combat. i also disabled all other addons with no change.

**Comment by wolfrunner86** [comment]
and i also just tried deleting the cache/interface/wtf and just installed bestride and still only works on 1/4

**Comment by wolfrunner86** [comment]
ok so i think i figured it out, but why it was only working on 1 i dont know since they all use the same profile, the traveltotravel i had to uncheck then recheck for it to enable.
i am assuming it is not on by default which is why the fresh installs wasnt working.
Thanks for the working on picking up this addon and thanks for implemnting the choosable pass and repair mount something i suggested somewhere at one time

**Comment by DanSheps** [comment]
Question, are you trying to prioritize travel forms over mounts?  Travel form only triggers when you are moving or falling.

**Comment by wolfrunner86** [comment]
yeah i know ya gotta be moving, once i unchecked and rechecked traveltotravel it started working

**Comment by Mindlessgalaxy** [comment]
Sorry if I made things worse for you Wolfrunner86, was only trying to assist, but sounds like I caused you a fair amount of grief for no real good reason.  I am thrilled you have worked it all out and that DanSheps is helping you.  He has been awesome and very helpful with not only taking up this addon, but being so receptive to constructive feedback and why I wanted and want to help where possible.  Probably not really my place to, but again just wanted to help if you got to read my post first and it worked, which it obviously didn't.  Also sounds like you have had a fair bit of experience with addons anyway.

All the best and again sorry for mucking you around if I have,

Mindlessgalaxy.

**Comment by wolfrunner86** [comment]
Mindlessgalaxy you were trying to help so thank you.

**Comment by DanSheps** [comment]
Have you had a chance to try this?

**Comment by wolfrunner86** [comment]
i had fixed it by toggling the traveltotravel option, in the text file it was not in there until i unchecked and rechecked it.

**Comment by wolfrunner86** [comment]
you can close this, i have not been able to replicate this again, after toggling off/on it has worked without a problem, thanks for all your work!

**Comment by DanSheps** [comment]
Thanks for the update
