### ISSUE TITLE
Mounting Not Working On Island Expeditions!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#68]
Hi,

Just thought I would let you know I did my first and then another Island Expedition and the key binding works for Blink on my Troll level 117 Horde Mage, however the key binding is not working at all for mounting, which is a little annoying, but easy enough to over come by putting a mount in action bar for islands only. Not sure about other toons yet or Ally faction.

Hope that is a start to help out for you and also fresh install as well and using the current version you do have up v1.0,1.

Thanks again.

Mindlessgalaxy,

**Comment by SeiriCerin** [comment]
Dunno if this is helpful, but it's here ^^

7x BeStride\BeStride_Logic.lua:809: attempt to index global 'playerTable' (a nil value)
BeStride\BeStride_Logic.lua:809: in function `IsDeathKnight'
BeStride\BeStride_Logic.lua:273: in function `IsDeathKnightAndSpecial'
BeStride\BeStride_Logic.lua:134: in function `GroundMountButton'
BeStride\BeStride_ActionButton.lua:74: in function `PreClick'
BeStride\BeStride_ActionButton.lua:25: in function <BeStride\BeStride_ActionButton.lua:25>

Locals:
self = <table> {
 MageSpecial = <function> defined @BeStride\BeStride_Logic.lua:1190
 IsDeathKnight = <function> defined @BeStride\BeStride_Logic.lua:808
 DruidCanCat = <function> defined @BeStride\BeStride_Logic.lua:917
 IsPaladin = <function> defined @BeStride\BeStride_Logic.lua:853
 DruidFlightFormPriority = <function> defined @BeStride\BeStride_Logic.lua:1158
 IsSpecialZone = <function> defined @BeStride\BeStride_Logic.lua:557
 Shaman = <function> defined @BeStride\BeStride_Logic.lua:510
 NeedToRepair = <function> defined @BeStride\BeStride_Logic.lua:786
 Mage = <function> defined @BeStride\BeStride_Logic.lua:462
 IsFalling = <function> defined @BeStride\BeStride_Logic.lua:667
 CheckLoanedMount = <function> defined @BeStride\BeStride_Logic.lua:685
 IsDruid = <function> defined @BeStride\BeStride_Logic.lua:826
 PassengerMountButton = <function> defined @BeStride\BeStride_Logic.lua:211
 IsPriest = <function> defined @BeStride\BeStride_Logic.lua:862
 CanBroom = <function> defined @BeStride\BeStride_Logic.lua:774
 PriestCanLevitate = <function> defined @BeStride\BeStride_Logic.lua:1042
 PaladinCanDivineSteed = <function> defined @BeStride\BeStride_Logic.lua:1030
 RepairMountButton = <function> defined @BeStride\BeStride_Logic.lua:198
 IsRepairable = <function> defined @BeStride\BeStride_Logic.lua:589
 ShamanCanGhostWolf = <function> defined @BeStride\BeStride_Logic.lua:1054
 MageBlink = <function> defined @BeStride\BeStride_Logic.lua:1207
 DemonHunterCanGlide = <function> defined @BeStride\BeStride_Logic.lua:965
 DeathKnightWraithWalk = <function> defined @BeStride\BeStride_Logic.lua:1081
 SpecialZone = <function> defined @BeStride\BeStride_Logic.lua:575
 IsMountable = <function> defined @BeStride\BeStride_Logic.lua:647
 IsDruidTraveling = <function> defined @BeStride\BeStride_Logic.lua:1125
 IsShaman = <function> defined @BeStride\BeStride_Logic.lua:880
 RogueCanSprint = <function> defined @BeStride\BeStride_Logic.lua:1066
 WGActive = <function> defined @BeStride\BeStride_Logic.lua:1343
 Priest = <function> defined @BeStride\BeStride_Logic.lua:496
 IsMonkAndSpecial = <function> defined @BeStride\BeStride_Logic.lua:344
 DeathKnight = <function> defined @BeStride\BeStride_Logic.lua:420
 PriestLevitate = <function> defined @BeStride\BeStride_Logic.lua:1284
 Combat = <function> defined @BeStride\BeStride_Logic.lua:224
 Rogue = <function> defined @BeStride\BeStride_Logic.lua:516
 IsMonk = <function> defined @BeStride\BeStride_Logic.lua:844
 GroundMountButton = <function> defined @BeStride\BeStride_Logic.lua:128
 UseRepair = <function> defined @BeStride\BeStride_Logic.lua:743
 GetRidingSkill = <function> defined @BeStride\BeStride_Logic.lua:1331
 CanRepair = <function> defined @BeStride\BeStride_Logic.lua:763
 ShamanGhostWolf = <function> defined @BeStride\BeStride_Logic.lua:1318
 RogueSprint = <function> defined @BeStride\BeStride_Logic.lua:1301
 PaladinDivineSteed = <function> defined @BeStride\BeStride_Logic.lua:1267
 MonkZenFlight = <function> defined @BeStride\BeStride_Logic.lua:1251
 IsPaladinAndSpecial = <function> defined @BeStride\BeStride_Logic.lua:362
 IsDemonHunter = <function> defined @BeStride\BeStride_Logic.lua:817
 IsMage = <function> defined @BeStride\BeStride_Logic.lua:835
 IsUnderwater = <function> defined @AddOn

**Comment by Mindlessgalaxy** [comment]
Hi Again,

I also did get an error, but only just noticed after seeing the one above. I apologise for missing something so important in the reporting. Thank you SeiriCerin for helping, as I am not sure if my report was with enough info like normal.

Here is my error as well:

			["message"] = "Interface\\AddOns\\BeStride\\BeStride-1.0.0.lua:540: attempt to index local 'map' (a nil value)",
			["time"] = "2018/10/28 23:10:24",
			["locals"] = "self = <table> {\n SetDefaultModuleLibraries = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:367\n EnableModule = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:332\n modules = <table> {\n }\n baseName = \"BeStride\"\n IterateEmbeds = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:442\n AddCommonMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:506\n GetMap = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:356\n Printf = <function> defined @Interface\\AddOns\\Ace3\\AceConsole-3.0\\AceConsole-3.0.lua:69\n SetDefaultModulePrototype = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:409\n GetProfiles = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:178\n IsEnabled = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:451\n DisableModule = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:350\n AddRepairMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:526\n buildMountTables = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:444\n RegisterMessage = <function> defined @Interface\\AddOns\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:90\n UnregisterMessage = <function> defined @Interface\\AddOns\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:153\n UpdateBindings = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:189\n db = <table> {\n }\n CreateActionButton = <function> defined @Interface\\AddOns\\BeStride\\BeStride_ActionButton.lua:7\n EventUpdateKeyBinding = <function> defined @Interface\\AddOns\\BeStride\\BeStride_Events.lua:5\n SetEnabledState = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:424\n enabledState = true\n DBSetMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:418\n RegisterEvent = <function> defined @Interface\\AddOns\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:90\n ItemToName = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:532\n DBGetMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:408\n IterateModules = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:437\n GetMapUntil = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:538\n DBGetClassSetting = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:430\n SetKeyBindings = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:308\n BuildMasterMountTable = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:449\n Upgrade = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:208\n OnInitialize = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:127\n UnregisterAllEvents = <function> defined @Interface\\AddOns\\Ace3\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:174\n GetModule = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:210\n defaultModuleLibraries = <table> {\n }\n EventNewMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride_Events.lua:1\n UnregisterChatCommand = <function> defined @Interface\\AddOns\\Ace3\\AceConsole-3.0\\AceConsole-3.0.lua:111\n EventCombatExit = <function> defined @Interface\\AddOns\\BeStride\\BeStride_Events.lua:19\n GetName = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:279\n SpellToName = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:345\n NewMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:184\n name = \"Bestride\"\n DBSet = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:388\n DBSetSetting = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:426\n Disable = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:314\n Print = <function> defined @Interface\\AddOns\\Ace3\\AceConsole-3.0\\AceConsole-3.0.lua:54\n DBSetClassSetting = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:438\n DBGet = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:366\n AddPassengerMount = <function> defined @Interface\\AddOns\\BeStride\\BeStride.lua:520\n IsModule = <function> defined @Interface\\AddOns\\Ace3\\AceAddon-3.0\\AceAddon-3.0.lua:46",
			["stack"] = "Interface\\AddOns\\BeStride\\BeStride-1.0.0.lua:540: in function <Interface\\AddOns\\BeStride\\BeStride.lua:538>\n(tail call): ?\nInterface\\AddOns\\BeStride\\BeStride_Logic.lua:690: in function `CheckLoanedMount'\nInterface\\AddOns\\BeStride\\BeStride_Logic.lua:676: in function `IsLoanedMount'\nInterface\\AddOns\\BeStride\\BeStride_Logic.lua:49: in function `Regular'\nInterface\\AddOns\\BeStride\\BeStride_ActionButton.lua:46: in function `PreClick'\nInterface\\AddOns\\BeStride\\BeStride_ActionButton.lua:25: in function <Interface\\AddOns\\BeStride\\BeStride_ActionButton.lua:25>",
			["session"] = 16,
			["counter"] = 44,

Hope that helps a bit, but also please be aware that I am having a crisis in my life at the moment and am making a lot of mistakes.  Although helping with this addon and playing the game is keeping me sane for now, and I prefer not to say more than that.  It is a pleasure to help and I will keep doing my best.  I apologise also for saying now and not, NOT lol.  Just goes to show I really am not with it in the last few reports I have made.

Thanks again.

Mindlessgalaxy.

**Comment by DanSheps** [comment]
The playertable bug should be resolved with 1.0.7.

The map error you should not be getting, that is a straight call to the C_Map API, but I will put in some protection there just in case in the next build.

**Comment by Mindlessgalaxy** [comment]
Just to let you know, I unfortunately didn't get to do any island expeditions.  I will try tonight, but so far it is working perfectly in everyway for me and I would be shocked if you didn't have it corrected either.  I will try as I said and I do have that version installed, as in 1.0.7.

Thanks again and have  a lovely day.

Mindlessgalaxy.

**Comment by mcc1** [comment]
still has bug in 1.0.8
`80x BeStride\BeStride-1.0.7.lua:549: attempt to index local 'map' (a nil value)
BeStride\BeStride-1.0.7.lua:549: in function <BeStride\BeStride.lua:547>
(tail call): ?
BeStride\BeStride_Logic.lua:690: in function `CheckLoanedMount'
BeStride\BeStride_Logic.lua:676: in function `IsLoanedMount'
BeStride\BeStride_Logic.lua:49: in function `Regular'
BeStride\BeStride_ActionButton.lua:46: in function `PreClick'
BeStride\BeStride_ActionButton.lua:25: in function <BeStride\BeStride_ActionButton.lua:25>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "BeStride"
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 AddCommonMount = <function> defined @BeStride\BeStride.lua:515
 GetMap = <function> defined @BeStride\BeStride.lua:365
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 GetProfiles = <function> defined @BeStride\BeStride.lua:187
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 Frame = <function> defined @BeStride\BeStride.lua:172
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 AddRepairMount = <function> defined @BeStride\BeStride.lua:535
 buildMountTables = <function> defined @BeStride\BeStride.lua:453
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UpdateBindings = <function> defined @BeStride\BeStride.lua:198
 db = <table> {
 }
 CreateActionButton = <function> defined @BeStride\BeStride_ActionButton.lua:7
 EventUpdateKeyBinding = <function> defined @BeStride\BeStride_Events.lua:5
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 DBSetMount = <function> defined @BeStride\BeStride.lua:427
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 ItemToName = <function> defined @BeStride\BeStride.lua:541
 DBGetMount = <function> defined @BeStride\BeStride.lua:417
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 bestrideOptionsFrame = <unnamed> {
 }
 GetMapUntil = <function> defined @BeStride\BeStride.lua:547
 DBGetClassSetting = <function> defined @BeStride\BeStride.lua:439
 SetKeyBindings = <function> defined @BeStride\BeStride.lua:317
 BuildMasterMountTable = <function> defined @BeStride\BeStride.lua:458
 Upgrade = <function> defined @BeStride\BeStride.lua:217
 OnInitialize = <function> defined @BeStride\BeStride.lua:128
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UpdateOverrideBindings = <function> defined @BeStride\BeStride.lua:207
 defaultModuleLibraries = <table> {
 }
 EventNewMount = <function> defined @BeStride\BeStride_Events.lua:1
 UnregisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 EventCombatExit = <function> defined @BeStride\BeStride_Events.lua:18
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 SpellToName = <function> defined @BeStride\BeStride.lua:354
 NewMount = <function> defined @BeStride\BeStride.lua:193
 name = "Bestride"
 DBSet = <function> defined @BeStride\BeStride.lua:397
 orderedModules = <table> {
 }
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 Print = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 DBSetClassSetting = <function> defined @BeStride\BeStride.lua:447
 DBGet = <function> defined @BeStride\BeStride.lua:375
 AddPassengerMount = <function> defined @BeStride\BeStride.lua:529
 IsModule = <function> `

**Comment by DanSheps** [comment]
What zone were you in?

**Comment by mcc1** [comment]
actually I have played 5 island expeditions. all of them are not working. I have forgotten the name. I will have another try today.

**Comment by DanSheps** [comment]
Alright, I will have to try and get into an expedition and see what the API returns for the map, it seems like it isn't returning a proper map.

**Comment by DanSheps** [comment]
Next time someone goes into an expedition, could you type:

/br map

And give me the output?

Thanks

**Comment by Mindlessgalaxy** [comment]
Hi,

I have done one for you on one island and the interesting thing is the key binding does not work for mounting, BUT it does for my Pally Class mount ability only.  So not sure what that means at all?  I am Ally Pally Level 16 on Nagrand.  Screen Shot hopefully attached for you as well and error below:

[Debug]1036, The Dread Chain,3,0.

![wowscrnshot island mount issues](https://user-images.githubusercontent.com/9031328/47907422-56322400-dedf-11e8-9012-23a022d76256.jpg)

Will try with Horde later either same level toon or slightly higher, and hopefully with Mage so I can try Blink?  The Island that I did first have issues on is named Kunza Kunza and again Horde.

Just want to confirm mounting not working, but key binding for my pally class does work all the time without any errors or issues at all.  I just hope that means something to you and helps this all make some sense.  Also hope I have given you enough information.  If you want more debugging done, please just ask and describe what you want and how to do it like above and I will always endeavour to do my best to help you out :).

Thanks heaps,

Mindlessgalaxy.

**Comment by DanSheps** [comment]
Could you do the /br map command in the next island expedition please?

**Comment by SeiriCerin** [comment]
Got a chance to do this for you. But the addon was working properly xD I will do it again if i get the problem on an other island.

[14:48:50] [Debug]981,Un'gol Ruins,6,947
[14:48:50] [Debug]947,Azeroth,1,946
[14:48:50] [Debug]946,Cosmic,0,

**Comment by DanSheps** [comment]
> [Debug]1036, The Dread Chain,3,0.

Hey Mindless, I didn't notice this before, so sorry.  I think I see the problem now, it looks like it is sending an invalid parent map to command, which is why it fails.

I will see if I can add in a check for this and just return if there is no parent map.

**Comment by DanSheps** [comment]
> Got a chance to do this for you. But the addon was working properly xD I will do it again if i get the problem on an other island.
> 
> [14:48:50] [Debug]981,Un'gol Ruins,6,947
> [14:48:50] [Debug]947,Azeroth,1,946
> [14:48:50] [Debug]946,Cosmic,0,

Thanks, this really helps.  It looks like some of the expeditions are not on any specific cosmic map, so that definitely helps.

**Comment by mcc1** [comment]
I have tried one this is the log
```
[Debug]1036,恐懼群島,3,0 
```

and I also got error while type /br map
```
1x BeStride\BeStride_Debug.lua:72: attempt to index local 'map' (a nil value)
BeStride\BeStride_Debug.lua:72: in function <BeStride\BeStride_Debug.lua:66>
(tail call): ?
BeStride\BeStride_Debug.lua:58: in function `DebugGetMaps'
BeStride\BeStride-1.0.7.lua:356: in function `?'
Ace3\AceConsole-3.0\AceConsole-3.0-7.lua:94: in function `?'
FrameXML\ChatFrame.lua:4734: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4396: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4432: in function <FrameXML\ChatFrame.lua:4428>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
 Debug = <function> defined @BeStride\BeStride_Debug.lua:48
 DebugGetMaps = <function> defined @BeStride\BeStride_Debug.lua:56
 Notice = <function> defined @BeStride\BeStride_Debug.lua:36
 Verbose = <function> defined @BeStride\BeStride_Debug.lua:42
 Emergency = <function> defined @BeStride\BeStride_Debug.lua:3
 Info = <function> defined @BeStride\BeStride_Debug.lua:23
 DebugGetMapUntil = <function> defined @BeStride\BeStride_Debug.lua:66
 DebugGetMapName = <function> defined @BeStride\BeStride_Debug.lua:61
 Critical = <function> defined @BeStride\BeStride_Debug.lua:10
 Error = <function> defined @BeStride\BeStride_Debug.lua:16
 Informational = <function> defined @BeStride\BeStride_Debug.lua:30
}
locID = 0
filter = 0
map = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'map' (a nil value)"
```

**Comment by DanSheps** [comment]
Yeah, thanks, I see the issue here.

It is because "GetMapUntil()" is looking for a upper bound on the 3rd item in the table (mapType).

I have pushed out an update, please switch your release type to "beta" to view it.  When you get into an expedition, please try it again, as well as the `/br map` command.

Thanks

**Comment by Mindlessgalaxy** [comment]
Hi Dan,

Thanks so much for all your assistance and help with this, as well as pleased I and the others were able to be of assistance to make it much easier for you to diagnose the actual issue/fault.  I am not playing today (Saturday), although I will be playing tomorrow and will give the new version a go then, I also like the idea of making it a Beta to try reduce the load of tickets you get and the extra pressure, of course if you are getting any at all?  I will let you know tomorrow if I find any issues with it, but getting to know you and your work -- lets just say I would be very surprised if it didn't work.

Thanks heaps,

Mindless.

**Comment by SeiriCerin** [comment]
The first one i did today only gave me one line:
`[14:05:42] [Debug]1036,The Dread Chain,3,`

then the 2nd gave me this
```
[14:22:10] [Debug]981,Un'gol Ruins,6,947
[14:22:10] [Debug]947,Azeroth,1,946
[14:22:10] [Debug]946,Cosmic,0,
```

It's also summoning flying mounts, even though it's a no-fly zone (and I have that option turned off because drakes running on the ground looks so ridiculous!).
