### ISSUE TITLE
No Vashj'ir Mount Use In Addon!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [DanSheps/Bestride#72]
Hi again.

I have been doing the Hallowed End Bucket treats to get the Hearthstone and some pets.  I didn't even pick up at any stage until I entered this zone that there is no mount setup in the addon at all for the Vashj'ir Mounts, for their underwater zone of Vashj'ir.  There are 3 mounts in total and here are their ID's although I do not know the map ID sorry, I did try WOWHead, but for the life of me I have no idea how to provide you or assist with a map ID and I would really love to know just out of curiosity if you don't mind sharing please?

Mounts:

Vashj'ir Seahorse ID: 75207.
Vashj'ir Subdued Seahorse ID; 98718.
Reins Of Poseidus ID: 67151.

I am not sure if it makes any difference, but the mounts go at 450% as well underwater.  Not sure if this has any impact on coding, as they are obviously not the same as any other mount for speed?

In all honesty to me this is a very low priority, although it probably should be in the addon especially considering it is mount and zone related.  It isn't hard to get around by putting the mount in a place holder in your action bars if you have one free, but lets be honest it isn't that hard and to me if you can get to it sometime down the track it would be great and if not who is in the zone that often for that long, but I shouldn't really speak for others.  The Hallowed End event finishes tomorrow sometime and not one person has identified this issue at all as far as I can tell.  I suppose I am trying to help by saying concentrate on whatever you think you need to do with your addon (like you need me to tell you that lol) and as you know I am only trying to help, just wish my stupid anxiety would go away so I could just be clear and concise, sorry about that.

If you want to know anything else, just leave a comment here, as I now check everyday and I didn't report this issue last night as I was terribly tired and trying without any success to get the stupid Headless Horseman Mount lol.

All the best,

Mindlessgalaxy.

**Comment by DanSheps** [comment]
So, swimming mounts seem to be working as expected.  The only thing is it will summon fathom dweller if you have it in the rotation.

Are you saying there should be a zone preference for these three mounts?

**Comment by Mindlessgalaxy** [comment]
Hi,

Yes the mounts I have mentioned only work in their zone and no other zones at all.  Not sure why blizzard went down this path, although they have.  The other water mounts work as you would expect perfectly.  So yes, simply put it is a zone issue only and I cannot and do not know how to get you map ids.  Wish I did so I could help you more with the information I give you.

Hope that helps, but yes you are also understanding me correctly.

Mindlessgalaxy.

**Comment by DanSheps** [comment]
/br map will generate the map id's

I think the problem is though, it summons the regular ones fine (Subdued seahorse, Poseidus is not 450% either, it shares the same speed as Subdued and other mounts).

I will add in a priority for Vashj'ir for the vashj'ir seahorse and then that will be it.  But it is summoning the swimming mounts correctly from what I can see.

**Comment by Mindlessgalaxy** [comment]
Hi Dan,

I hear what you are saying, but when I highlight the buff of the mounts for Vashj'ir Seahorse ID: 75207 it states very clearly 450% and it goes go much faster than flying etc.  That is what I was basing that off, and if all of them go at that speed or the so called speed, then it really doesn't matter -- I agree totally.  Not sure why the Blizzard buffs would say 450% though and yes I have checked in game again to confirm so I don't make myself look like a fool lol.  Maybe just a blizzard API issue or something?

I have done some more research and it is a mount only that does 450% underwater (some references to it on WOWHead and other places as well and is only for the relevant zone.  On a quick side note, they originally only started out at 280% speed apparently.  If you are interested in trying you can just run this script and it will disclose the details of the speed of any mount etc you are using at the time and the Seahorse is by far the quickest so far:

/script x=GetUnitSpeed("player") DEFAULT_CHAT_FRAME:AddMessage(format("Speed: %d yds/sec, %.1f kph, %.1f mph, %d%% normal run speed",x,x*3600/1093.6133,x*45/22,x/7*100))

Results:
Abyssal Seahorse: 
25 yrds/sec, 85.5 kph, 53.1 mph, 371% normal run speed.

Sea Turtle:
18 yrds/sec, 62.2 kph, 38.6 mph, 269% normal run speed.

Tested with Master Riding in the Abyssal Depths.

Hope that helps, and if not interested all good and just ignore the post.  Again only trying to help out is all :).  Not sure, it may be of assistance later on for you, or not lol.  I have not tried the script, although those who have had documented this evidence so far:

Thanks in advance.

Mindlessgalaxy.

**Comment by DanSheps** [comment]
Yeah, I am probably just going to do a single check for Vashj'ir and swimming and if that is the case then only summon the seahorse.
