### ISSUE TITLE
Broken in BFA

### ISSUE THREAD

**Issue by Hampen555** [DanSheps/Bestride#9]
UI works but the mount macros dont :/

**Comment by Malivil** [comment]
`Date: 2018-07-18 17:56:04
ID: 49
Error occured in: Global
Count: 1
Message: ..\AddOns\bestride\Bestride_Logic.lua line 211:
   attempt to call global 'GetCurrentMapContinent' (a nil value)
Debug:
   bestride\Bestride_Logic.lua:211: PreClick()
   [string "*:PreClick"]:1:
      [string "*:PreClick"]:1
   [C]: Click()
   ..\FrameXML\ChatFrame.lua:1626: ?()
   ..\FrameXML\ChatFrame.lua:4695:
      ..\FrameXML\ChatFrame.lua:4662
   [C]: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4383:
      ..\FrameXML\ChatFrame.lua:4382
   [C]: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:2874:
      ..\FrameXML\ChatFrame.lua:2867
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:345: handler()
   ..\FrameXML\SecureTemplates.lua:623:
      ..\FrameXML\SecureTemplates.lua:571
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:266:
      ..\FrameXML\SecureHandlers.lua:263
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:296:
      ..\FrameXML\SecureHandlers.lua:279
   (tail call): ?
Locals:
self = <table> {
 CreateMountCheckBox = <function> defined @Interface\AddOns\bestride\Bestride.lua:413
 Frames = <function> defined @Interface\AddOns\bestride\Bestride_Gui.lua:461
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "bestride"
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 ReloadMounts = <function> defined @Interface\AddOns\bestride\Bestride.lua:341
 ReSort = <function> defined @Interface\AddOns\bestride\Bestride.lua:242
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 Filter = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:528
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 PreClick = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:196
 BuildStandardMountTable = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:110
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 GetArgs = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 ReputationCheck = <function> defined @Interface\AddOns\bestride\Bestride.lua:253
 db = <table> {
 }
 SetMacroButtonCombat = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:516
 MonkSpecial = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:349
 SetEnabledState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 ItemToName = <function> defined @Interface\AddOns\bestride\Bestride.lua:267
 ForcePassengerMount = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:304
 IterateModules = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 AlphaSortProfileDB = <function> defined @Interface\AddOns\bestride\Bestride.lua:224
 Druids = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:377
 UpdateBindingButtons = <function> defined @Interface\AddOns\bestride\Bestride.lua:435
 Keybinding = <function> defined @Interface\AddOns\bestride\Bestride.lua:470
 OnInitialize = <function> defined @Interface\AddOns\bestride\Bestride.lua:115
 UnregisterAllEvents = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 GetModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 BuildPassengerTable = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:85
 defaultModuleLibraries = <table> {
 }
 PriestOrMageSpecial = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:333
 UnregisterChatCommand = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 GetName = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 SpellToName = <function> defined @Interface\AddOns\bestride\Bestride.lua:262
 name = "Bestride"
 bestrideOpFrame = <unnamed> {
 }
 IsUsableMount = <function> defined @Interface\AddOns\bestride\Bestride.lua:218
 orderedModules = <table> {
 }
 CheckLoanerMount = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:470
 Disable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 UseStrider = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:443
 GetRepairMount = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:49
 Swimming = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:399
 ClassCheck = <function> defined @Interface\AddOns\bestride\Bestride_Logic.lua:364
 CheckNagrandSpecialMount = <function> defined @Interface\AddOns\bestride
AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  NPCScanOverlay, v7.3.0.1
  Altoholic, vr183
  Archy, v7.3.2.1
  Atlas, vv1.43.06
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasLegion, vv1.43.03
  AtlasMistsofPandaria, vv1.43.00
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWrathoftheLichKing, vv1.43.01
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  AtlasMajorCitiesEnhanced, vv1.15
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  Bartender4, v4.8.1
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  bestride, v0.0.2
  CTBagMod, v
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v8.0.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  EasyMail, v7.0
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  ExecutiveAssistant, v1.1.9k
  ExtVendor, v1.6.2
  FactionAddict, v1.48
  GatherMate2, v1.42
  Grail, v095
  HandyNotes, vv1.5.2
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesSuramarTelemancy, v1
  IceHUD, v1.11.1
  Informant, v7.7.6000 (SwimmingSeadragon)
  MasterPlanA, vA
  MouseTooltip, v1.0
  MoveAnything, v16.3.2
  nehFragger, v1.3
  NPCScan, v8.0.1.1
  Omen, v3.2.0
  OmniCC, v7.3.1
  Overachiever, v1.0.0
  PersonalLootHelper, v2.03
  PetBattleMaster, v7.0.4
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerJournal, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  Prat30, vr1150      
  Prat30Libraries, v
  Quester, v8.0.1.0
  Recount, vv7.3.5c
  sct, v7.1
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  Stubby, v7.7.6000 (SwimmingSeadragon)
  TimerBars, v1.2
  Titan, v5.13.1.70300
  TitanBag, v5.13.1.70300
  TitanClock, v5.13.1.70300
  TitanGold, v5.13.1.70300
  TitanGuild, v7.0.3.4
  TitanLocation, v5.13.1.70300
  TitanLootType, v5.13.1.70300
  TitanMail, v7.35
  TitanPerformance, v5.13.1.70300
  TitanRepair, v5.13.1.70300
  TitanSpeed, v7.3.001
  TitanVolume, v5.13.1.70300
  TitanXP, v5.13.1.70300
  Wholly, v066
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=bdc)

`

**Comment by Daeymien** [comment]
Change line 211 in Bestride_Logic.lua from:
`if((GetCurrentMapContinent() == 7 or zone == "Tanaan Jungle") and not IsSpellKnown(191645)) then`

to

`if (WorldMapFrame:GetMapID('player') == nil) then`
`        WorldMapFrame:Show()`
`        WorldMapFrame:Hide()`
`	end`
`	if((WorldMapFrame:GetMapID('player') == 7 or zone == "Tanaan Jungle") and not IsSpellKnown(191645)) then`

and line 221 from 
`	if ( GetCurrentMapContinent() == 8 and not IsSpellKnown(233368) ) then
`

to

`	if ( WorldMapFrame:GetMapID('player') == 8 and not IsSpellKnown(233368) ) then
`

**Comment by DanSheps** [comment]
@Malivil Thanks for the report
@Daeymien Thanks for the pull request, I will review it shortly and most likely approve it and push it out as a release.
